server.port=1111
eureka.instance.hostname=localhost

# Запрещаем серверу регистрироваться в самом себе
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false

# ⚡ НАСТРОЙКИ АГРЕССИВНОГО ТАЙМАУТА ДЛЯ HIGHLOAD
# Включаем жесткую очистку реестра: сервер проверяет живые сервисы каждые 5 секунд (вместо 60с)
eureka.server.eviction-interval-timer-in-ms=5000

# Отключаем режим самосохранения (Self-Preservation).
# В локальном контуре и Pet-проектах он вреден, так как заставляет Эврику бесконечно держать в реестре упавшие сервисы
eureka.server.enable-self-preservation=false

# Переводим фоновые задачи синхронизации Эврики на виртуальные потоки Loom
spring.threads.virtual.enabled=true

spring.thymeleaf.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
